# Generated by Django 3.0.6 on 2020-06-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20200611_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='retailer_email',
            new_name='retailerEmail',
        ),
    ]
