# Generated by Django 3.0.6 on 2020-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20200613_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailerEmail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
