# Generated by Django 3.0.6 on 2020-06-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20200613_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
