# Generated by Django 3.0.6 on 2020-09-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100, null=True)),
                ('totalCost', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('waitTime', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailerEmail', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200, null=True)),
                ('totalCost', models.CharField(max_length=100, null=True)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
    ]
