# Generated by Django 3.0.6 on 2020-06-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200605_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='retailer',
        ),
    ]
