# Generated by Django 3.0.6 on 2020-06-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_order_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
