# Generated by Django 3.0.6 on 2020-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_product_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='totalCost',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='wait_time',
            new_name='waitTime',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_cost',
            new_name='totalCost',
        ),
    ]
