# Generated by Django 3.0.6 on 2020-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20200614_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailerEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
