# Generated by Django 3.0.6 on 2020-06-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200529_1630'),
        ('users', '0002_auto_20200531_2207'),
    ]

    operations = [
    ]
