# Generated by Django 3.0.6 on 2020-05-31 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200531_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='User_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='farmer', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='surname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first_name'),
        ),
    ]
