# Generated by Django 3.0.6 on 2020-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200531_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='Farmer', max_length=50),
        ),
    ]
