# Generated by Django 3.0.6 on 2020-06-01 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200531_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='User_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='farmer', max_length=50),
        ),
    ]
