# Generated by Django 3.0.6 on 2020-06-03 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200602_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='id number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
