# Generated by Django 3.0.6 on 2020-06-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200603_2212'),
        ('users', '0002_auto_20200529_1630'),
    ]

    operations = [
    ]
