# Generated by Django 3.0.6 on 2020-06-07 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200608_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='idNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True, verbose_name='id number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer')], default='farmer', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=150, unique=True, verbose_name='surname'),
        ),
    ]
