# Generated by Django 3.0.6 on 2020-06-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200608_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='typeUser',
        ),
    ]
