# Generated by Django 3.0.6 on 2020-06-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200607_1124'),
        ('users', '0013_auto_20200608_1648'),
    ]

    operations = [
    ]
